version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/service
      - npm install
      - npm run build
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - build/**/*
    - node_modules/**/*
    - .babelrc
    - LICENSE
    - README.md